#!/bin/bash
#################################################################### License ###
# unp-inplace - a tiny wrapper script for the unarchiver unp.
# Written in 2011 by Ady Rosebrigg (adyrosebrigg@gmail.com)
#
# To the extent possible under law, the author(s) have dedicated all 
# copyright and related and neighboring rights to this software to the 
# public domain worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see 
# <http://creativecommons.org/publicdomain/zero/1.0/>.
############################################################### Info Message ###
if ! [[ -n $@ ]]; then

echo "  Script: unp-inplace"
echo "  Author: Ady Rosebrigg"
echo "  Usage : unp-inplace [files] - unpacks archives into their own directories."

############################################################ Unpack Archives ###
else
for ARG in "$@"		# For each argument (archive file):
do

ARCHIVEPATH=$(find "$ARG" -type f)	# Get the full path to the archive,
cd "$(dirname "$ARCHIVEPATH")"		# cd to its parent directory,
unp -U "$ARCHIVEPATH"			# unp the file there,
cd -					# then return to the shell's last dir.

done			# and reloop for the next archive.
fi
